 const mudar_modo = document.getElementById("modoEscuroToggle")
 const body = document.body
 const foto = document.getElementById("foto")
 const eu = document.getElementById("eu")
 const link = document.getElementById("link")
 const link1 = document.getElementById("link1")
 const link2 = document.getElementById("link2")
 const icon = document.getElementById("icon")
 const icon1 = document.getElementById("icon1")
 const icon2 = document.getElementById("icon2")
 const icon3 = document.getElementById("icon3")
 const pe = document.getElementById("pé")
 mudar_modo.addEventListener('change', () => {

    body.classList.toggle("light")
    foto.classList.toggle("light")
    eu.classList.toggle("light")
    link.classList.toggle("light")
    link1.classList.toggle("light")
    link2.classList.toggle("light")
    icon.classList.toggle("light")
    icon1.classList.toggle("light")
    icon2.classList.toggle("light")
    icon3.classList.toggle("light")
    pe.classList.toggle("light")
 })